name: Pre-merge
on:
  merge_group:
    types: [checks_requested]
jobs:
  pre-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.14.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Bump version, build, commit, and merge changes
        run: |
          npm ci
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch --no-git-tag-version
          PACKAGE_VERSION=$(node -pe "require('./package.json').version")
          npm run build
          git add .
          git commit -m "Build $PACKAGE_VERSION"
          git push origin ${{ github.event.pull_request.head.ref }}