name: Pre-merge
on:
  pull_request:
    types: [ closed ]
jobs:
  pre-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.14.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Bump version, build, commit, and merge changes
        if: github.event.pull_request.merged == true
        run: |
          npm ci
          git config user.name spont4e
          git config user.email spont4e@users.noreply.github.com
          npm version patch --no-git-tag-version
          PACKAGE_VERSION=$(node -pe "require('./package.json').version")
          npm run build
          git add .
          git commit -m "Build $PACKAGE_VERSION"
          git push origin master
